# Generated by Django 3.2.9 on 2021-11-23 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=250)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nombre_estac', models.CharField(max_length=50)),
                ('nro_espacios', models.IntegerField(default=0)),
                ('espacio_disponible', models.IntegerField(default=0)),
                ('telefono', models.CharField(max_length=50)),
                ('disponibilidad', models.CharField(max_length=70)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpark.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nusuario', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=250)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('nro_placa', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('imagen_vehiculo', models.ImageField(blank=True, null=True, upload_to='vehiculos')),
                ('id_tipovehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpark.tipovehiculo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpark.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=70)),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id_estacionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpark.estacionamiento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpark.usuario')),
                ('nro_placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpark.vehiculo')),
            ],
        ),
    ]
