# Generated by Django 3.2.9 on 2021-11-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpark', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamiento',
            name='id_usuario',
        ),
    ]
